ci:
  autoupdate_commit_msg: "MAINT: upgrade lock files"
  autoupdate_schedule: quarterly

  autofix_commit_msg: "MAINT: implement pre-commit autofixes"
  skip:
    - check-jsonschema
    - tombi-format
    - tombi-lint

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: v1.2.0
    hooks:
      - id: tombi-format
      - id: tombi-lint
        args: [--error-on-warnings]

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.8.1
    hooks:
      - id: prettier

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
      - id: check-jsonschema
        args: ["--schemafile", "schema.json"]
        files: ^models/.*\.(json|yaml|yml)$

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v10.0.1
    hooks:
      - id: cspell
        language_version: 25.9.0

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.1
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec
