ci:
  autoupdate_commit_msg: "MAINT: upgrade lock files"
  autoupdate_schedule: quarterly

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-jsonschema
        args: ["--schemafile", "schema.json"]
        files: ^models/.*\.(json|yaml|yml)$

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v10.0.0
    hooks:
      - id: cspell
        language_version: 25.9.0

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.8.1
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.4
    hooks:
      - id: toml-sort
        args: [--in-place]
        exclude: (?x)^(.*/Manifest\.toml|.*/Project\.toml)$
