name: Documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: |-
    ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}

env:
  CI: true
  FORCE_COLOR: yes

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Julia cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: |
            julia-${{hashFiles('Manifest.toml')}}-${{hashFiles('**/*.jl')}}
          restore-keys: |
            julia-${{hashFiles('Manifest.toml')}}
            julia
          path: |
            ~/.julia/
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          cache: true
      - name: Jupyter cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: |
            jupyter-cache-${{hashFiles('pixi.lock')}}-${{hashFiles('docs/*/*.qmd', 'models/*.json')}}
          path: |
            **/.jupyter_cache
      - name: General caches
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: |
            home-cache-${{hashFiles('pixi.lock')}}-${{hashFiles('docs/*/*.qmd', 'models/*.json')}}
          restore-keys: |
            home-cache-${{hashFiles('pixi.lock')}}
            home-cache
          path: |
            ~/.cache
      - run: pixi run doc
      - if: always()
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: docs/_build/html

  preview:
    if: >-
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: github-pages
      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Check out preview branch
        run: |
          mkdir preview
          cd preview
          git init
          git remote add origin https://x-access-token:${{ secrets.PAT }}@github.com/RUB-EP1/amplitude-serialization-pr-preview
          if git fetch --depth=1 origin gh-pages; then
            git checkout -B gh-pages FETCH_HEAD
            git rm -rf .
          else
            git checkout --orphan gh-pages
          fi
      - name: Extract artifact
        run: |
          tar xf artifact.tar -C preview
          rm artifact.tar
      - name: Commit results
        working-directory: preview
        run: |
          touch .nojekyll
          git add -A
          if git rev-parse --verify HEAD; then
            git commit --amend -m "https://github.com/RUB-EP1/amplitude-serialization/pull/${{ github.event.number }} preview at https://rub-ep1.github.io/amplitude-serialization-pr-preview"
          else
            git commit -m "https://github.com/RUB-EP1/amplitude-serialization/pull/${{ github.event.number }} preview at https://rub-ep1.github.io/amplitude-serialization-pr-preview"
          fi
      - name: Push results to GitHub Pages
        working-directory: preview
        run: git push origin gh-pages --force
      - name: Show link to PR preview
        run: echo "Documentation preview available on [rub-ep1.github.io/amplitude-serialization-pr-preview](https://rub-ep1.github.io/amplitude-serialization-pr-preview)" >> $GITHUB_STEP_SUMMARY

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: >-
      github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
